services:
  - type: web
    name: renaperghost
    env: python  
    plan: free
    buildCommand: "pip install -r requirements.txt"  
    startCommand: "python Request.py"  
    envVars:
      - key: CERT_PASSWORD
        value: sape  
    build:
      commands:
        - cp cert.pfx /etc/secrets/cert.pfx  


