services:
  - type: web
    name: renaperghost
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python your_main_script.py"
    envVars:
      - key: CERT_PASSWORD
        value: sape  # Your certificate password

